all_details_message = {
    'mr': f"जगातील कोरोणा व्हायरस(कोविड-19) ची माहीत:\n\n "
          f"टोटल संख्या: \n "
          f"सक्रिय संख्या\n"
          f"बरे झालेल्यांची संख्या\n"
          f"टोटल मृत्यूंची संख्या",
    'en': f"Global covid19 information:\n\n "
          f"Total cases\n "
          f"Active cases\n "
          f"Recovered cases\n"
          f"Total deaths"
}

country_specific_message = {
    'mr': f" मधील कोरोणा व्हायरस (कोविड-19) ची माहीत:\n\n"
          f"टोटल संख्या: \n "
          f"आजची संख्या: \n"
          f"सक्रिय संख्या: \n "
          f"बरे झालेल्यांची संख्या: "
          f"गांभीर्यांची संख्या: "
          f"टोटल मृत्यूंची संख्या: \n "
          f"आजची मृत्यूंची संख्या: ",
    'en': f"s corona virus (COVID-19) Info: \n\n"
          f"Total cases\n"
          f"Today's cases:\n"
          f"Active cases\n"
          f"Recovered cases\n"
          f"Total deaths\n"
          f"Today's deaths"
}

indian_states_list = [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Ladakh',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Mizoram',
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Tamil Nadu',
    'Telangana',
    'Unknown', 'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal'
]

countries = [
    "Andorra",
    "Afghanistan",
    "Antigua and Barbuda",
    "Albania",
    "America",
    "Armenia",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Azerbaijan",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Brunei Darussalam",
    "Bolivia",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Ivory Coast",
    "Chile",
    "Cameroon",
    "People's Republic of China",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Eritrea",
    "Ethiopia",
    "Finland",
    "Fiji",
    "France",
    "Gabon",
    "Georgia",
    "Ghana",
    "The Gambia",
    "Guinea",
    "Greece",
    "Guatemala",
    "Haiti",
    "Guinea-Bissau",
    "Guyana",
    "Honduras",
    "Hungary",
    "Indonesia",
    "Republic of Ireland",
    "Israel",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Kiribati",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Lebanon",
    "Liechtenstein",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Madagascar",
    "Marshall Islands",
    "Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Mauritania",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Kingdom of the Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Slovenia",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "Sao Tome and Principe",
    "Syria",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Vanuatu",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Algeria",
    "Bosnia and Herzegovina",
    "Cambodia",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Croatia",
    "East Timor",
    "El Salvador",
    "Equatorial Guinea",
    "Grenada",
    "Kazakhstan",
    "Laos",
    "Federated States of Micronesia",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Morocco",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "Serbia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Swaziland",
    "Switzerland",
    "USA",
    "United Arab Emirates",
    "United Kingdom",
    "Taiwan",
    "Hong Kong",
    "Kosovo",
    "Puerto Rico",
]
